[tools]
go = "latest"
java = "latest"
node = "lts"
python = "latest"
usage = "latest"

[settings]
# let mise paths take precedence https://mise.jdx.dev/configuration/settings.html#activate_aggressive
activate_aggressive = true
# delete cache files not been accessed in this amount of time https://mise.jdx.dev/configuration/settings.html#cache_prune_age
cache_prune_age = "7d"
# disable hints https://mise.jdx.dev/configuration/settings.html#disable_hints
disable_hints = ["*"]
# use default GOPATH ${GOPATH:-$HOME/go}/bin https://mise.jdx.dev/configuration/settings.html#go_set_gobin
go_set_gobin = false
# default yes to prompts https://mise.jdx.dev/configuration/settings.html#yes
yes = true
